name: gym_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.3.3=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py37h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2020.0=166
  - isort=4.3.21=py37_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37hc9558a2_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - olefile=0.46=py37_0
  - openssl=1.1.1=h7b6447c_0
  - pandas=1.0.1=py37h0573a6f_0
  - pcre=8.43=he1b5a44_0
  - pip=20.0.2=py37_1
  - pthread-stubs=0.4=h14c3975_1001
  - pylint=2.4.4=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=45.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.11.0
    - aiohttp==3.7.3
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - box2d-py==2.3.8
    - cachetools==4.0.0
    - cffi==1.14.0
    - chardet==3.0.4
    - cloudpickle==1.2.2
    - cython==0.29.15
    - decorator==4.4.2
    - defusedxml==0.6.0
    - einops==0.3.0
    - entrypoints==0.3
    - fasteners==0.15
    - flatbuffers==1.12
    - fsspec==2021.7.0
    - future==0.18.2
    - gast==0.3.3
    - glfw==1.10.1
    - google-api-core==1.24.1
    - google-api-python-client==1.12.8
    - google-auth==1.24.0
    - google-auth-httplib2==0.0.4
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.52.0
    - grpcio==1.32.0
    - gym==0.16.0
    - h5py==2.10.0
    - httplib2==0.18.1
    - idna==2.8
    - imageio==2.6.1
    - imgaug==0.4.0
    - importlib-metadata==3.4.0
    - int-date==0.1.8
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lockfile==0.12.2
    - markdown==3.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - monotonic==1.5
    - mpl-finance==0.10.0
    - multidict==5.1.0
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.0
    - nest-asyncio==1.4.3
    - networkx==2.5
    - notebook==6.2.0
    - numpy==1.21.1
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - opencv-python==4.2.0.32
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0
    - pycparser==2.19
    - pydeprecate==0.3.0
    - pydrive==1.3.1
    - pyglet==1.4.10
    - pygments==2.7.4
    - pyrsistent==0.17.3
    - pytesseract==0.3.4
    - python-chess==0.30.1
    - pytorch-lightning==1.3.8
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - pyzmq==21.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.18.1
    - seaborn==0.11.1
    - send2trash==1.5.0
    - shapely==1.7.1
    - six==1.15.0
    - slackclient==2.9.3
    - stockstats==0.3.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - tifffile==2021.2.1
    - torch==1.7.1
    - torchmetrics==0.4.1
    - torchsummary==1.5.1
    - torchvision==0.8.2
    - tornado==6.1
    - tqdm==4.46.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - uritemplate==3.0.1
    - urllib3==1.25.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.0
    - wheel==0.36.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yarl==1.6.3
    - zipp==3.4.0
prefix: /home/vador/anaconda3/envs/gym_env

